<?php

namespace ssstrz\ZakladnikBundle\Entity;

use Doctrine\ORM\EntityRepository;
use ssstrz\ZakladnikBundle\Entity;
/**
 * BookmarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookmarkRepository extends EntityRepository
{
    public function getSuggestionFor(User $user, $greaterThan = 1) 
    {
        /*
SELECT 
    *
 , count(u.id) as sub_counter
FROM
    zakladnik.Bookmark b
left join
    user_bookmark ub ON b.id = ub.bookmark_id
left join
	User u on ub.user_id = u.id
and b.id not in (
select subb.id from Bookmark subb
left join user_bookmark subub on subb.id = subub.bookmark_id 
left join User subu on subub.user_id = subu.id
where subu.id = 10)
where u.id <> 1
group by u.id
having sub_counter > 2
;
         */
        $qb = $this->createQueryBuilder('sb');
        $subscribtions = $qb
                ->select('sb.id')->leftJoin('sb.subscribers', 'su')->where('su.id = 10')
                ->getQuery()->getDQL()
        ;
        
        $suggestions = $this->createQueryBuilder('b')
                ->select('b', 'u')
                ->addSelect('count(u.id) as subscriberCounter')
                ->leftJoin('b.subscribers', 'u')
                ->where('u <> :user')
                ->andWhere($qb->expr()->notIn('b.id', $subscribtions))
                ->groupBy('b.id')
                ->having('subscriberCounter > :greaterThan')
                ->setParameter('user', $user)
                ->setParameter('greaterThan', $greaterThan)->getQuery()->getResult()
        ;

        return $suggestions;
    }
    public function findUrl($url) 
    {
        $qb = $this->createQueryBuilder('b')
                ->select('b')
                ->where('b.url LIKE :url')
                ->setParameter('url', $url)
                ->setMaxResults(1);
        
        return $qb->getQuery()->getResult();
    }
}
