ssstrz_zakladnik_add:
    pattern:  /add
    defaults: { _controller: ssstrzZakladnikBundle:Bookmark:add }
    
ssstrz_zakladnik_my:
    pattern:  /my
    defaults: { _controller: ssstrzZakladnikBundle:Bookmark:my }

ssstrz_zakladnik_suggestion:
    pattern:  /suggestion
    defaults: { _controller: ssstrzZakladnikBundle:Bookmark:suggestion }

ssstrz_zakladnik_remove:
    pattern:  /remove
    defaults: { _controller: ssstrzZakladnikBundle:Bookmark:remove }
    
ssstrz_zakladnik_homepage:
    pattern:  /
    defaults: { _controller: ssstrzZakladnikBundle:Default:index }

ssstrz_zakladnik_register:
    pattern: /register
    defaults: { _controller: ssstrzZakladnikBundle:Account:register }
    
ssstrz_zakladnik_register_create:
    pattern: /register/create
    defaults: { _controller: ssstrzZakladnikBundle:Account:create }
    
ssstrz_zakladnik_login:
    pattern: /login
    defaults: { _controller: ssstrzZakladnikBundle:Account:login }
    
ssstrz_zakladnik_logout:
    pattern: /logout
    defaults: { _controller: ssstrzZakladnikBundle:Account:logout }
    
ssstrz_zakladnik_test:
    pattern: /test
    defaults: { _controller: ssstrzZakladnikBundle:Account:test }
   
login_check:
  path: /login_check

login:
  path: /login_standard
  defaults: { _controller: ssstrzZakladnikBundle:Account:login }

account:
    path: /
my:
    pattern: /my
    defaults: { _controller: ssstrzZakladnikBundle:Bookmark:my }

add:
    pattern: /add
    defaults: { _controller: ssstrzZakladnikBundle:Bookmark:add }

remove:
    pattern: /remove
    defaults: { _controller: ssstrzZakladnikBundle:Bookmark:remove }

suggestion:
    pattern: /suggestion
    defaults: { _controller: ssstrzZakladnikBundle:Bookmark:suggestion }
