ssstrz_zakladnik_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ssstrzZakladnikBundle:Default:index }

ssstrz_zakladnik_register:
    pattern: /register
    defaults: { _controller: ssstrzZakladnikBundle:Account:register }
ssstrz_zakladnik_register_create:
    pattern: /register/create
    defaults: { _controller: ssstrzZakladnikBundle:Account:create }