security:
    encoders:
        ssstrz\ZakladnikBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
            
    role_hierarchy:
        ROLE_ADMIN:   ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
      
    providers:
        administrators:
            entity: {class: ssstrz\ZakladnikBundle\Entity\User, property: username}
        
    firewalls:
      admin_area:
        pattern: ^/admin
        http_basic: ~
      secured_area:
        pattern: ^/
        anonymous: ~
        form_login:
          login_path: login
          check_path: login_check
        
    access_control:
      - { path: ^/hello, roles: ROLE_USER }
        
